# Estágio 2: Configuração do Nginx
FROM nginx:alpine

# Copia a configuração do Nginx para o container
COPY nginx.conf /etc/nginx/nginx.conf

# Exponha a porta 80 para o Nginx
EXPOSE 80

# Define o comando para iniciar o Nginx
CMD ["nginx", "-g", "daemon off;"]